services:
  app:
    build: .
    container_name: shomoysoft_web
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - "3000:3000" # Expose container port to host machine
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 5s
      retries: 5
    restart: always
